[Tests] City Crud
NicolasMitre/city_pass_microservice pull request #17
Opened 2020-06-23 14:58 UTC by rakanishu37

Tasks#12  #21 #22

2020-06-25 14:45 UTC, Nicolas-Melluso approved these changes

2020-06-25 14:46 UTC, Nicolas-Melluso requested changes
Tiene conflictos

2020-06-25 16:59 UTC, MaruCagnoli approved these changes

2020-06-26 02:54 UTC, ghost requested changes

2026-04-15 15:00 UTC, Nicolas-Melluso commented
@copilot resolve the merge conflicts in this pull request

2026-04-15 15:23 UTC, Nicolas-Melluso approved these changes
Hola! Tanto tiempo 🤣 me tomé la libertad de revisar este repositorio con Copilot y supervisión humana para ajustar algunas cositas, en general son cuestiones relacionadas a los tipos, a la seguridad, a los tests y demases cosas

2026-04-15 15:23 UTC, merged